name: Build and Test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm ci and build
        run: |
          npm install
      - uses: actions/upload-artifact@main
        with:
          name: package artifacts
          path: public/

  run-npm-test:
    runs-on: ubuntu-latest
    needs: run-npm-build
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@main
        with:
          name: package artifacts
          path: public
      - name: npm ci, and test
        run: |
          npm install
          npm test
        env:
          CI: true

